### ISSUE TITLE
working on ssl irc?

### ISSUE THREAD

**Issue by ffuentese** [michaelShriver/ircom#1] opened 2022-05-06 02:54 UTC
I know this is very simple but could it also work on a SSL based IRC server like tilde.chat? I tried to connect it threw an error

**Comment by michaelShriver** [comment] 2022-05-09 22:47
libircclient has support for SSL when compiled with --enable-openssl, but I have not been able to successfully initialize an SSL session. The issue seems to be within libircclient, but I am at a loss to troubleshoot it.

**Comment by michaelShriver** [comment] 2022-05-11 22:58
This issue is caused by a bug in libircclient when it is compiled against newer versions of openssl. This patch by @anthonyc-r fixes the issue: https://sourceforge.net/p/libircclient/patches/9/

I've forked libircclient and applied the patch at https://github.com/michaelShriver/libircclient. To install it run:
```
./configure --enable-openssl --enable-shared
make && sudo make install
```
After that, recompile ircom against the new library

Cheers,
-- Michael

**Comment by ffuentese** [comment] 2022-05-12 00:24
Wait a second, where did you test this version? I couldn't connect to the server :

Could not connect or I/O error.

For reference:

ircom irc.tilde.chat [nick] [room]

**Comment by michaelShriver** [comment] 2022-05-12 00:31
You're right, I was a little premature in closing this. I still need to add the functionality to my code.

**Comment by michaelShriver** [comment] 2022-05-13 03:50
I added SSL support with the command line switch -t. You may also have to specify the port with -p. Invocation has changed, use --usage for more information.

**Closed as completed** 2022-05-13 04:14 UTC
Labels: enhancement

**Comment by ffuentese** [comment] 2022-05-13 22:55
It's complaining about argp.h when compiling in the OpenBSD machine

```
$ make CFLAGS="-I$HOME/.local/include -L$HOME/.local/lib" 
cc -I/home/ffuentes/.local/include -L/home/ffuentes/.local/lib ircom.c arguments.c handlers.c functions.c  -lircclient -lpthread -lcrypto -lssl -o ircom
In file included from ircom.c:1:
./arguments.h:3:10: fatal error: 'argp.h' file not found
#include <argp.h>
         ^~~~~~~~
1 error generated.
In file included from arguments.c:2:
./arguments.h:3:10: fatal error: 'argp.h' file not found
#include <argp.h>
         ^~~~~~~~
1 error generated.
*** Error 1 in /home/ffuentes/ircom (Makefile:7 'ircom')
```

I'll test it on Manjaro too but it doesn't work on OpenBSD

**Comment by michaelShriver** [comment] 2022-05-13 23:00
*BSD doesn't have a version of glibc that includes argp.h. It should build on Linux. You can also try the argp-standalone port for OpenBSD
